name: Continuous Integration
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: [graalvm@, adopt@1.11]
    name: ${{ matrix.os }} -- ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.jdk }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          yarn --help
          sbt "frontend/test:compile" \
              "jsBridge06/publishLocal" \
              "jsBridge10/publishLocal" \
              "backend/test" \
              "frontend/testOnly bloop.ScalaVersionsSpec" \
              "frontend/testOnly -bloop.ScalaVersionsSpec" \
              "millBloop/compile" \
              "mavenBloop/compile" \
              "jsBridge10/test" \
              "sbtBloop013/publishLocal" \
              "sbtBloop10/publishLocal" \
              "frontend/it:run" \
              "frontend/runMain bloop.util.CommandsDocGenerator --test" \
              "frontend/runMain bloop.util.CommandsDocGenerator --out ../docs/cli-reference.md" \
              "frontend/testOnly -bloop.ScalaVersionsSpec" \
              "frontend/it:run" \
              "gradleBloop212/test"
        shell: bash
